TravelTripProjee/Models/Siniflar/Iletisim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TravelTripProjee.Models.Siniflar
{
    public class Iletisim
    {
        [Key]
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string Mail { get; set; }
        public string Konu { get; set; }
        public string Mesaj { get; set; }
    }
}

TravelTripProjee/Controllers/IletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTripProjee.Models.Siniflar;

namespace TravelTripProjee.Controllers
{
    public class IletisimController : Controller
    {
        // GET: Iletisim
        Context c = new Context();
        public ActionResult Index()
        {
            var deger = c.AdresBlogs.ToList();
            return View(deger);
        }
        [HttpGet]
        public PartialViewResult MesajGonder()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult MesajGonder(Iletisim i)
        {
            var deger = c.Iletisims.Add(i);
            c.SaveChanges();
            return PartialView();
        }
    }
}

TravelTripProjee/Views/Iletisim/Index.cshtml
@using TravelTripProjee.Models.Siniflar
@model List<AdresBlog>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!DOCTYPE HTML>
<html>
<head>
    <title>Personal Blog a Blogging Category Flat Bootstarp  Responsive Website Template | Single :: w3layouts</title>
    <link href="/web1/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="/web1/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!--end slider -->
    <!--script-->
    <script type="text/javascript" src="/web1/js/move-top.js"></script>
    <script type="text/javascript" src="/web1/js/easing.js"></script>
    <!--/script-->
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 900);
            });
        });
    </script>
    <!---->

</head>


<div class="contact">
    <div class="wrap">
        <div class="contact-top">
            <h3>Bizimle İletişime Geçin</h3>
            <p>Bize değerli fikirlerinizi ve görüşlerinizi bildirmek için bizimle iletişime geçebilirsiniz.</p>
        </div>
        @Html.Action("MesajGonder", "Iletisim")
        <div class="clear" style="margin-top:20px;"></div>
        <div class="contact-bottom">
            <div class="contact-left">
                <div class="contact-add">
                    @foreach (var item in Model)
                    {
                        <h3>Adres</h3>
                        <p>@item.AdresAcik</p>
                        <p>Telefon:@item.Telefon</p>
                        <p>Fax:@item.Telefon</p>
                        <p>Mail:<a href="@item.Mail">@item.Mail</a></p>
                    }
                </div>
            </div>

            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
</div>

TravelTripProjee/Views/Iletisim/MesajGonder.cshtml
<div class="content-form">
    <h3>Mesaj Gönderin</h3>
    <form method="post">
        <input type="text" placeholder="AdSoyad" name="AdSoyad" required />
        <input type="text" placeholder="Konu" name="Konu" required />
        <input type="text" placeholder="Mail" name="Mail" required />
        <textarea placeholder="Mesaj" name="Mesaj"></textarea>
        <input type="submit" value="GÖNDER" />
    </form>
</div>